Repository Simplon-hdf/bots-discord-api, pull requests merged in 2025-02, with the labels that each got.

#1 chore: add readme and CODEOWNERS
  .github/CODEOWNERS
  README.md
Labels: documentation, enhancement

#2 docs: add ROADMAP.md
  ROADMAP.md
Labels: documentation

#4 build: configure docker for dev and prod environments and add ci pipeline
  .dockerignore
  .env.development
  .env.production
  .github/workflows/deploy.yml
  Dockerfile.dev
  Dockerfile.prod
  docker-compose.dev.yml
  docker-compose.prod.yml
  nginx/nginx.conf
  src/main.ts
Labels: enhancement

#10 feat(86c21g631, 86c21g5t2): add the promotion module add the channel module
  README.md
  package-lock.json
  package.json
  src/channels/channels.controller.spec.ts
  src/channels/channels.controller.ts
  src/channels/channels.module.ts
  src/channels/channels.service.spec.ts
  src/channels/channels.service.ts
  src/channels/dto/create-channel.dto.ts
  src/channels/dto/update-channel.dto.ts
  src/channels/entities/channel.entity.ts
  src/promotions/dto/create-promotion.dto.ts
  src/promotions/dto/update-promotion.dto.ts
  src/promotions/entities/promotion.entity.ts
  src/promotions/promotions.controller.spec.ts
  src/promotions/promotions.controller.ts
  src/promotions/promotions.module.ts
  src/promotions/promotions.service.spec.ts
  src/promotions/promotions.service.ts
  vitest.config.ts
Labels: documentation, enhancement

#22 feat(T86c21mpkf / T86c21mx5c): add Questions module and Question entity
  src/app.module.ts
  src/questions/dto/create-question.dto.ts
  src/questions/dto/update-question.dto.ts
  src/questions/entities/question.entity.ts
  src/questions/questions.controller.spec.ts
  src/questions/questions.controller.ts
  src/questions/questions.module.ts
  src/questions/questions.service.spec.ts
  src/questions/questions.service.ts
Labels: enhancement

#24 feat(86c21mpkf/86c21mxd9/86c21mx5c/86c21mpmv): fix questions and answers modules
  src/answers/answers.module.ts
  src/answers/answers.service.ts
  src/questions/entities/question.entity.ts
  src/questions/questions.service.ts
Labels: enhancement

#25 feat(86c21mu9g): Implement Resources Module with CRUD Operations
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/reports/dto/create-report.dto.spec.ts
  src/reports/dto/create-report.dto.ts
  src/reports/dto/update-report.dto.ts
  src/reports/entities/report.entity.ts
  src/reports/reports.controller.spec.ts
  src/reports/reports.controller.ts
  src/reports/reports.integration.spec.ts
  src/reports/reports.module.ts
  src/reports/reports.service.spec.ts
  src/reports/reports.service.ts
  src/resources/dto/create-resource.dto.spec.ts
  src/resources/dto/create-resource.dto.ts
  src/resources/dto/update-resource.dto.ts
  src/resources/entities/resource.entity.ts
  src/resources/resources.controller.spec.ts
  src/resources/resources.controller.ts
  src/resources/resources.integration.spec.ts
  src/resources/resources.module.ts
  src/resources/resources.service.spec.ts
  src/resources/resources.service.ts
Labels: enhancement, help wanted

#38 feat: add swagger decorater, normalizer dependencies, refactor guilds and campuses
  README.md
  src/app.module.ts
  src/campuses/campuses.controller.spec.ts
  src/campuses/campuses.controller.ts
  src/campuses/campuses.module.ts
  src/campuses/campuses.service.spec.ts
  src/campuses/campuses.service.ts
  src/campuses/dto/create-campus.dto.ts
  src/campuses/dto/update-campus.dto.ts
  src/campuses/entities/campus.entity.ts
  src/categories/categories.controller.spec.ts
  src/categories/categories.controller.ts
  src/categories/categories.service.spec.ts
  src/categories/categories.service.ts
  src/categories/dto/create-category.dto.ts
  src/categories/dto/update-category.dto.ts
  src/categories/entities/category.entity.ts
  src/channels/channels.controller.spec.ts
  src/channels/channels.controller.ts
  src/channels/channels.module.ts
  src/channels/channels.service.spec.ts
  src/channels/channels.service.ts
  src/channels/dto/create-channel.dto.ts
  src/channels/dto/update-channel.dto.ts
  src/channels/entities/channel.entity.ts
  src/guilds-templates/dto/create-guild-template.dto.ts
  src/guilds-templates/dto/update-guild-template.dto.ts
  src/guilds-templates/entities/guild-template.entity.ts
  src/guilds-templates/guilds-templates.controller.ts
  src/guilds-templates/guilds-templates.service.ts
  src/guilds/dto/create-guild.dto.ts
  src/guilds/dto/update-guild.dto.ts
  src/guilds/entities/guild.entity.ts
  src/guilds/guilds.controller.spec.ts
  src/guilds/guilds.controller.ts
  src/guilds/guilds.module.ts
  src/guilds/guilds.service.spec.ts
  src/guilds/guilds.service.ts
  src/main.ts
  src/members-informations/dto/create-member-informations.dto.ts
  src/members-informations/dto/update-member-informations.dto.ts
  src/members-informations/entities/member-information.entity.ts
  src/members-informations/entities/member-informations.entity.ts
  src/members-informations/members-informations.controller.ts
  src/members-informations/members-informations.module.ts
  src/members-informations/members-informations.service.spec.ts
  src/members-informations/members-informations.service.ts
  src/promotions/dto/create-promotion.dto.ts
  src/promotions/dto/update-promotion.dto.ts
  src/promotions/entities/promotion.entity.ts
  src/promotions/promotions.controller.spec.ts
  src/promotions/promotions.controller.ts
  src/promotions/promotions.module.ts
  src/promotions/promotions.service.spec.ts
  src/promotions/promotions.service.ts
Labels: enhancement

#39 feat(86c21g54x): add discord-users
  src/app.module.ts
  src/discord-users/discord-users.controller.spec.ts
  src/discord-users/discord-users.controller.ts
  src/discord-users/discord-users.module.ts
  src/discord-users/discord-users.service.spec.ts
  src/discord-users/discord-users.service.ts
  src/discord-users/dto/create-discord-user.dto.ts
  src/discord-users/dto/update-discord-user.dto.ts
  src/discord-users/entities/discord-user.entity.ts
Labels: enhancement

#41 docs(86c23xjae): add Swagger documention to moderator-actions module
  src/moderator-actions/dto/create-moderator-action.dto.ts
  src/moderator-actions/dto/update-moderator-action.dto.ts
  src/moderator-actions/entities/moderator-action.entity.ts
  src/moderator-actions/moderator-actions.controller.ts
Labels: documentation

#42 docs(86c21mr5n): add Swagger documentation to xp-transactions module
  src/xp-transactions/dto/create-xp-transaction.dto.ts
  src/xp-transactions/dto/update-xp-transaction.dto.ts
  src/xp-transactions/entities/xp-transaction.entity.ts
  src/xp-transactions/xp-transactions.controller.ts
  src/xp-transactions/xp-transactions.module.ts
  src/xp-transactions/xp-transactions.service.ts
Labels: documentation

#46 test(86c21mpmv): implement answer module test coverage
  src/answers/answers.controller.spec.ts
  src/answers/answers.integration.spec.ts
  src/answers/answers.service.spec.ts
Labels: enhancement

#48 docs(86c21mtz5): add response examples to Swagger documentation in votes module
  src/votes/votes.controller.ts
Labels: documentation

#47 docs(86c21mpmv): implement swagger documentation for answers module
  src/answers/answers.controller.ts
  src/answers/dto/create-answer.dto.ts
  src/answers/dto/update-answer.dto.ts
  src/answers/entities/answer.entity.ts
  src/main.ts
Labels: documentation

#49 feat(86c276v1r): implement relations between Member, MemberInformations, IdentificationRequest, DiscordUser and DashboardAccount
  src/dashboard-accounts/dashboard-accounts.controller.ts
  src/dashboard-accounts/dashboard-accounts.service.spec.ts
  src/dashboard-accounts/dashboard-accounts.service.ts
  src/dashboard-accounts/dto/create-dashboard-account.dto.ts
  src/dashboard-accounts/entities/dashboard-account.entity.ts
  src/discord-users/discord-users.controller.spec.ts
  src/discord-users/discord-users.controller.ts
  src/discord-users/discord-users.service.spec.ts
  src/discord-users/discord-users.service.ts
  src/discord-users/dto/create-discord-user.dto.ts
  src/discord-users/dto/update-discord-user.dto.ts
  src/discord-users/entities/discord-user.entity.ts
  src/identification-requests/dto/create-identification-request.dto.ts
  src/identification-requests/entities/identification-request.entity.ts
  src/members-informations/dto/create-member-informations.dto.ts
  src/members-informations/entities/member-information.entity.ts
  src/members-informations/members-informations.service.ts
  src/members/dto/create-member.dto.ts
  src/members/entities/member.entity.ts
Labels: enhancement

#50 feat(86c27e488): add global validation pipe
  src/main.ts
Labels: enhancement

#51 feat(86c271jtx): Add relationship between Guild and Member entities
  src/app.module.ts
  src/guilds/entities/guild.entity.ts
  src/members/members.service.ts
Labels: enhancement

#54 fix(86c238tg2, 86c21g5d8): correct courses and dashboard accounts
  src/categories/entities/category.entity.ts
  src/channels/entities/channel.entity.ts
  src/courses/courses.controller.spec.ts
  src/courses/courses.controller.ts
  src/courses/courses.service.spec.ts
  src/courses/courses.service.ts
  src/courses/dto/create-course.dto.spec.ts
  src/courses/dto/create-course.dto.ts
  src/courses/entities/course.entity.ts
  src/dashboard-accounts/dashboard-accounts.controller.spec.ts
  src/dashboard-accounts/dashboard-accounts.controller.ts
  src/dashboard-accounts/dashboard-accounts.service.spec.ts
  src/dashboard-accounts/dto/create-dashboard-account.dto.spec.ts
  src/guilds/entities/guild.entity.ts
  src/promotions/entities/promotion.entity.ts
  src/roles/entities/role.entity.ts
Labels: enhancement

#57 refactor(86c21mpmv): improve answers module with pickable fields and English documentation
  src/answers/answers.controller.spec.ts
  src/answers/answers.controller.ts
  src/answers/answers.integration.spec.ts
  src/answers/answers.service.spec.ts
  src/answers/answers.service.ts
  src/answers/dto/create-answer-question.dto.ts
  src/answers/dto/create-answer.dto.ts
  src/answers/entities/answer.entity.ts
Labels: documentation, enhancement

#59 docs: Update Readme with endpoints
  README.md
Labels: documentation

#60 feat(86c21jw0n): guild Relations Implementation and Code Standardization
  README.md
  src/campuses/dto/create-campus.dto.ts
  src/campuses/entities/campus.entity.ts
  src/categories/categories.controller.spec.ts
  src/categories/categories.service.spec.ts
  src/categories/dto/create-category.dto.ts
  src/categories/dto/update-category.dto.ts
  src/categories/entities/category.entity.ts
  src/channels/channels.service.ts
  src/channels/dto/create-channel.dto.ts
  src/channels/entities/channel.entity.ts
  src/comments/comments.controller.spec.ts
  src/comments/comments.service.spec.ts
  src/comments/dto/create-comment.dto.ts
  src/comments/entities/comment.entity.ts
  src/courses/courses.service.ts
  src/courses/entities/course.entity.ts
  src/dashboard-accounts/dashboard-accounts.controller.ts
  src/dashboard-accounts/dashboard-accounts.service.spec.ts
  src/dashboard-accounts/dashboard-accounts.service.ts
  src/dashboard-accounts/dto/create-dashboard-account.dto.ts
  src/dashboard-accounts/entities/dashboard-account.entity.ts
  src/discord-users/discord-users.controller.spec.ts
  src/discord-users/discord-users.controller.ts
  src/discord-users/discord-users.service.spec.ts
  src/discord-users/discord-users.service.ts
  src/discord-users/dto/create-discord-user.dto.ts
  src/discord-users/dto/update-discord-user.dto.ts
  src/discord-users/entities/discord-user.entity.ts
  src/guilds-templates/dto/create-guild-template.dto.ts
  src/guilds-templates/entities/guild-template.entity.ts
  src/guilds/dto/create-guild.dto.ts
  src/guilds/entities/guild.entity.ts
  src/identification-requests/dto/create-identification-request.dto.ts
  src/identification-requests/entities/identification-request.entity.ts
  src/identification-requests/identification-requests.controller.spec.ts
  src/identification-requests/identification-requests.service.spec.ts
  src/identification-requests/identification-requests.service.ts
  src/members-informations/dto/create-member-informations.dto.ts
  src/members-informations/entities/member-information.entity.ts
  src/members-informations/members-informations.controller.spec.ts
  src/members-informations/members-informations.service.ts
  src/members/dto/create-member.dto.ts
  src/members/entities/member.entity.ts
  src/members/members.controller.spec.ts
  src/members/members.service.spec.ts
  src/members/members.service.ts
  src/promotions/dto/create-promotion.dto.ts
  src/promotions/entities/promotion.entity.ts
  src/roles/dto/create-role.dto.ts
  src/roles/entities/role.entity.ts
  src/roles/roles.controller.spec.ts
  src/roles/roles.service.spec.ts
  src/utils/pickable-discord-uuid-fields.ts
  src/utils/pickable-intern-uuid-fields.ts
  src/xp-transactions/entities/xp-transaction.entity.ts
  src/xp-transactions/xp-transactions.controller.ts
  src/xp-transactions/xp-transactions.service.ts
Labels: enhancement

#62 refactor(86c21mpmv): enhance error handling and update DTO usage
  src/answers/answers.controller.spec.ts
  src/answers/answers.controller.ts
  src/answers/answers.service.ts
Labels: enhancement

#65 refactor(86c21mpmv): simplify CreateAnswerDto
  src/answers/dto/create-answer.dto.ts
Labels: enhancement

#68 feat(86c21mpmv): add end-to-end tests and improve test configuration
  src/answers/answers.service.spec.ts
  src/answers/dto/create-answer.dto.ts
  src/main.ts
  tests/answers.e2e.spec.ts
Labels: enhancement

#75 docs(86c21mx4d/86c21mx8h): add swagger documentation
  src/questions/dto/create-question.dto.ts
  src/questions/questions.controller.ts
Labels: documentation

#77 refactor(86c21g3xx): simplify promotions retrieval logic
  src/members/members.service.ts
Labels: enhancement

#78 fix(86c21mpmv): fix integration tests and import paths
  src/answers/answers.integration.spec.ts
  src/questions/entities/question.entity.ts
Labels: enhancement

#81 feat(86c21mpmv): implement many-to-many relationship between answers and members
  src/answers/answers.integration.spec.ts
  src/answers/entities/answer.entity.ts
  src/members/entities/member.entity.ts
Labels: enhancement
